FROM amazon/aws-lambda-nodejs:16 as builder

ARG DUCKDB_VERSION=0.8.1
ARG DUCKDB_PRETEND_VERSION=0.8.2
ARG DUCKDB_COMMIT_HASH=474a0bd68377edb26f6047263a4c19784bb17aea
ARG ARCHITECTURE=x86_64

# Install dependencies
RUN yum update -y && \
  yum install git tar zip ninja-build make gcc-c++ python-pip glibc-devel \
    libstdc++-devel wget java-1.8.0-openjdk zip maven unixODBC-devel glibc-devel readline-devel \
    libcurl-devel expat-devel gettext unzip libffi-devel curl zlib-devel openssh \
    cpp.x86_64 sqlite-devel.x86_64 libtiff.x86_64 openssl11 openssl11-devel kernel-headers python-pip python3 -y && \
  yum remove cmake -y && \
  pip install cmake --upgrade

# Install and compile OpenSSL because the openssl-static package doesn't work
# RUN wget https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_0_2u.tar.gz && \
#   tar -xzvf OpenSSL_1_0_2u.tar.gz && \
#   mv openssl-OpenSSL_1_0_2u openssl-1.0.2u && \
#   cd openssl-1.0.2u && \
#   find ./ -type f -exec sed -i -e 's/\#\ define\ OPENSSL\_VERSION\_NUMBER/\#define\ OPENSSL\_VERSION\_NUMBER/g' {} \; && \
#   ./config --libdir=lib shared zlib-dynamic && \
#   make && \
#   make install

# Get DuckDB sources for specific commit
RUN mkdir -p /tmp/from-git && \
  cd /tmp/from-git && \
  git clone --branch main https://github.com/duckdb/duckdb.git && \
  cd duckdb && \
  git fetch --all --tags && \
  git checkout $DUCKDB_COMMIT_HASH

# Install vcpkg
RUN cd /tmp/from-git && \
  git clone https://github.com/Microsoft/vcpkg.git && \
  ./vcpkg/bootstrap-vcpkg.sh

# Copy custom Makefile (less parallelism)
COPY src/Makefile /tmp/from-git/duckdb/tools/nodejs/Makefile

# Copy custom configure.py
COPY src/configure.py /tmp/from-git/duckdb/tools/nodejs/configure.py

RUN echo ""

# Copy custom cmake extension config
COPY src/duckdb_extension_config.cmake /tmp/from-git/duckdb/tools/nodejs/duckdb_extension_config.cmake

# Configure
RUN cd /tmp/from-git/duckdb && \
  export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH" && \
  make extension_configuration && \
  USE_MERGED_VCPKG_MANIFEST=1 CMAKE_TOOLCHAIN_FILE="/tmp/from-git/vcpkg/scripts/buildsystems/vcpkg.cmake" EXTENSION_CONFIGS="/tmp/from-git/duckdb/tools/nodejs/duckdb_extension_config.cmake" EXTENSION_STATIC_BUILD=1 BUILD_HTTPFS=1 STATIC_OPENSSL=1 STATIC_LIBCPP=1 OPENSSL_STATIC=1 OPENSSL_ROOT_DIR=/usr/local/ssl BUILD_NODE=1 SETUPTOOLS_SCM_PRETEND_VERSION="v${DUCKDB_PRETEND_VERSION}" CMAKE_BUILD_PROGRAM="/usr/bin/make" CMAKE_VARS="-DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_INCLUDE_DIR=/usr/local/ssl/include -DOPENSSL_SSL_LIBRARY=/usr/local/ssl/lib -DOPENSSL_CRYPTO_LIBRARY=/usr/local/ssl/lib" CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) make

# Copy local binding definition
# COPY src/lib/duckdb-binding.js /tmp/from-git/duckdb/tools/nodejs/lib/duckdb-binding.js

# # Copy updated package.json
# COPY src/package.json /tmp/from-git/duckdb/tools/nodejs/package.json

# # Copy updated README.md
# COPY src/README.md /tmp/from-git/duckdb/tools/nodejs/README.md

# # Create zip file with layer contents
# RUN mkdir -p /tmp/build/nodejs/node_modules/duckdb/lib /tmp/build/nodejs/node_modules/duckdb/release /tmp/release && \
#   cp /tmp/from-git/duckdb/tools/nodejs/lib/*.js /tmp/build/nodejs/node_modules/duckdb/lib && \
#   cp /tmp/from-git/duckdb/tools/nodejs/README.md /tmp/build/nodejs/node_modules/duckdb/README.md && \
#   cp /tmp/from-git/duckdb/tools/nodejs/package.json /tmp/build/nodejs/node_modules/duckdb/package.json && \
#   cp /tmp/from-git/duckdb/tools/nodejs/duckdb.js /tmp/build/nodejs/node_modules/duckdb/duckdb.js && \
#   cp /tmp/from-git/duckdb/tools/nodejs/build/Release/duckdb.node /tmp/build/nodejs/node_modules/duckdb/release/duckdb.node && \
#   cd /tmp/build/nodejs/node_modules/duckdb && npm version ${DUCKDB_VERSION} || true && \
#   cd /tmp/build && zip -q -r /tmp/release/duckdb-layer-${ARCHITECTURE}.zip .
